name: SFDX CLI Deploy from repository
on: [push]
jobs:
    SFDX-CLI-Deploy:
        runs-on: ubuntu-latest
        steps:
        - apt update && apt -y install jq
            # Install Salesforce CLI
        - wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
        - mkdir -p ~/cli/sf
        - tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
        - export PATH=~/cli/sf/bin:$PATH
            # Output CLI version and plug-in information
        - sfdx --version
        - sfdx plugins --core
            
            # Authenticate to the Dev Hub using the server key
        - ls -lrt /opt/atlassian/pipelines/agent/build
        - pwd
        - sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY_PROD --jwtkeyfile /opt/atlassian/pipelines/agent/build/server.key --username $SF_USERNAME_PROD --setdefaultdevhubusername --setalias DevHub
        - sfdx force:org:list --all
            - sf org list
            - sfdx auth:list
            - sfdx force:org:display --targetusername $SF_USERNAME_PROD
            - sfdx force:package:list
            - sf package version create list
            # Create scratch org
            #- sfdx force:org:create --targetdevhubusername DevHub --setdefaultusername --definitionfile /opt/atlassian/pipelines/agent/build/config/project-scratch-def.json --setalias MyScratchOrg --wait 10 --durationdays 7
            - sfdx force:org:display --targetusername $SF_USERNAME_PROD
            - sf package version create --package dreamhouse1 --installation-key test1234 --wait 10 --codecoverage --targetdevhubusername DevHub
            - sf package version create list
            - sfdx force:package:list
            - sfdx auth:list
            - sf package install --wait 10 --publish-wait 10 --package dreamhouse1@1.0.0-1 --installation-key test1234 --no-prompt --target-org MyScratchOrg
            - sfdx force:apex:test:run --targetusername $SF_USERNAME_PROD --wait 10 --resultformat tap --codecoverage --testlevel $TESTLEVEL
            - sf package version promote --no-prompt --package dreamhouse1@1.0.0-1 --target-dev-hub DevHub
            - sf package install --wait 10 --publish-wait 10 --package dreamhouse1@1.0.0-1 --installation-key test1234 --no-prompt --target-org DevHub
